<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Receipt</title>
    <style>
        body {
            font-family: sans-serif;
            padding: 20px;
            line-height: 1.6;
        }

        .centered {
            text-align: center;
            margin-bottom: 20px;
        }

        .logo {
            width: 100px;
            height: auto;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #d1d5db;
        }

        th, td {
            text-align: left;
            padding: 10px;
        }

        th {
            background-color: #f3f4f6;
            color: #1f2937;
            width: 30%;
        }

        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #6b7280;
        }

        .divider {
            border-top: 1px solid #e5e7eb;
            margin-top: 20px;
        }
    </style>
</head>
<body>

    <div class="centered">
        <h2>UNIVERSITI TUN HUSSEIN ONN MALAYSIA</h2>
        <h3>STUDENT HOUSING CENTRE</h3>
        <p><strong>PAYMENT RECEIPT</strong></p>
    </div>

    <p>Thank you for your payment. Below are the payment details:</p>

    <table>
        <tr>
            <th>Payment ID</th>
            <td>{{ $payment->payment_id }}</td>
        </tr>
        <tr>
            <th>User</th>
            <td>{{ $payment->application->user->name }} ({{ $payment->application->user->email }})</td>
        </tr>
        <tr>
            <th>Application ID</th>
            <td>{{ $payment->application_id }}</td>
        </tr>
        <tr>
            <th>Amount</th>
            <td>RM {{ number_format($payment->amount, 2) }}</td>
        </tr>
        <tr>
            <th>Payment Method</th>
            <td>{{ $payment->payment_method }}</td>
        </tr>
        <tr>
            <th>Transaction ID</th>
            <td>{{ $payment->transaction_id ?? '-' }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ ucfirst($payment->payment_status) }}</td>
        </tr>
        <tr>
            <th>Paid On</th>
            <td>{{ $payment->payment_datetime->format('d M Y, h:i A') }}</td>
        </tr>
    </table>

    <div class="divider"></div>

    <div class="footer">
        This receipt is generated by RCARS UTHM system. No signature is required.
    </div>

</body>
</html>
